name = "ChemAlgebra"
uuid = "a20ab55d-8ed9-4713-9dce-23ab55040318"
version = "0.1.0"
authors = ["RTChou67 <3023207450@tju.edu.cn>"]

[deps]
Arpack = "7d9fca2a-8960-54d3-9f78-7d1dccf2cb97"
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
IterativeSolvers = "42fd0dbc-a981-5370-80f2-aaf504508153"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
Revise = "295af30f-e4ad-537b-8983-00126c2a3abe"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
Arpack = "0.5.4"
BenchmarkTools = "1.6.3"
IterativeSolvers = "0.9.4"
KrylovKit = "0.10.2"
LinearAlgebra = "1.12.0"
Printf = "1.11.0"
Random = "1.11.0"
Revise = "3.12.3"
SparseArrays = "1.12.0"
